### ISSUE TITLE
Slow decode since 0.6.2

### ISSUE THREAD

**Issue by sebastiw** [cvik/lejson#6]
The 0.7.0 version of lejson is like a turtle in comparison with 0.5.2:

The problem is between these tags:

0.6.2: Around 1 minute
```
37> binary:referenced_byte_size(B).
12538633
38> timer:tc(lejson, decode, [B]).
{58110055,
 #{<<"jobs">> =>
```

0.6.1: Around 1 second
```
2> timer:tc(lejson, decode, [B]).
{1052159,
 #{<<"jobs">> =>
```

The difference between these versions is that instead of doing `binary_to_list`, lejson matches out and build sub binaries.

**Comment by cvik** [comment]
Resolved by #7.
